# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: wiz.webhooks::lang.hooks.model

# Model Form Field configuration
form: $/wiz/webhooks/models/hook/fields.yaml

# Model Class name
modelClass: Wiz\Webhooks\Models\Hook

# Default redirect location
defaultRedirect: wiz/webhooks/hooks

# Create page
create:
    title: backend::lang.relation.create_name
    redirect: wiz/webhooks/hooks/update/:id
    redirectClose: wiz/webhooks/hooks

# Update page
update:
    title: backend::lang.relation.update_name
    redirect: wiz/webhooks/hooks
    redirectClose: wiz/webhooks/hooks

# Preview page
preview:
    title: backend::lang.relations.preview_name
