# ===================================
#  Relation Behavior Config
# ===================================

logs:
    label: wiz.webhooks::lang.logs.controller
    emptyMessage: wiz.webhooks::lang.logs.empty_message
    view:
        list: $/wiz/webhooks/models/log/columns.yaml
        toolbarButtons: delete
    manage:
        list: $/wiz/webhooks/models/log/columns.yaml
        form: $/wiz/webhooks/models/log/fields.yaml
